### ISSUE TITLE
Regarding autotests

### ISSUE THREAD

**Issue by Yerzhaisang** [1712n/infra-challenge#2]
Dear @darknessest  and @rsolovev ,

Can I change ```.github/workflows/build_autotests.yaml``` on my own branch just to test my solution?

Thank you for the response.

**Comment by rsolovev** [comment]
Hey @Yerzhaisang, I think it'll be easier (and faster) for you to just launch k6 locally via docker-compose or any other way. 
This action was not intended for running tests, just building the image and pushing it to our (internal) image repository.

**Comment by Yerzhaisang** [comment]
Got it, thank you;)
